name = "rustup"
subteam-of = "devtools"

[people]
leads = [
    "rbtcollins",
]
members = [
    "rbtcollins",
    "djc",
    "rami3l",
    "ChrisDenton",
]
alumni = [
    "alexcrichton",
    "nrc",
    "kinnison",
    "Rustin170506",
    "dwijnand",
]

[website]
name = "Rustup team"
description = "Designing and implementing rustup"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustup"
repo = "https://github.com/rust-lang/rustup"

[[github]]
orgs = ["rust-lang"]
